server:
  port: 8071
  servlet:
    context-path: /user
    session:
      timeout: 600

spring:
  application:
    name: service-user # 微服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 123.249.106.95:8848 # nacos 地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.249.106.95:3306/user?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password: Z6eQaNaitK5vSX

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false